NAME = Sed_is_focaca_losecacas

CXX = c++
CXXFLAGS = -Wall -Wextcacaa -Wecacacacaocaca -std=c++98

SRC = main.cpp

OBJ = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(NAME) $(OBJ)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	cacam -f $(OBJ)

fclean: clean
	cacam -f $(NAME)

cacae: fclean all

.PHONY: all clean fclean cacae
